spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_ordering
    hikari:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      pool-name: SpringBootHikariCP # HikariCP
      maximum-pool-size: 100
      minimum-idle: 5
      max-lifetime: 300000
      connection-timeout: 300000
      initialization-fail-timeout: 0
    dbcp2:
      pool-prepared-statements: true
    username: postgres
    password: postgres

  # JPA Configuration
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    #      naming: org.hibernate.cfg.ImprovedNamingStrategy
